# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

test:
    adapter: mysql
    encoding: utf8
    reconnect: true
    database: asnails
    pool: 5
    username: root
    password: 
    socket: /tmp/mysql.sock
  
production:
    adapter: mysql
    encoding: utf8
    reconnect: true
    database: asnails
    pool: 5
    username: root
    password: 
    socket: /tmp/mysql.sock